server:
  port: 8882
spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
#      uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: CONFIG-SERVER
    bus:
      trace:
        enabled: true
# 测试消息总线Bus
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
management:
  security:
    enabled: false